---
- name: Create data directory
  ansible.builtin.file:
    path: "{{ docker_data_folder }}/spaceapi_directory"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: "{{ docker_data_folder }}/spaceapi_directory/nginx.conf"
    owner: root
    group: root
    mode: "0755"

- name: Create service folder
  ansible.builtin.file:
    path: "{{ docker_folder }}/spaceapi_directory"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add docker-compose service configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ docker_folder }}/spaceapi_directory/.env"
    owner: root
    group: root
    mode: "0700"

- name: Add docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_folder }}/spaceapi_directory/docker-compose.yml"
    owner: root
    group: root
    mode: "0755"

- name: Run spaceapi directory
  community.docker.docker_compose_v2:
    project_src: /etc/docker/spaceapi_directory
    recreate: always
    build: true
    pull: always
    state: present
