- name: Configure metrics
  block:
    - file:
        path: "{{ docker_data_folder }}/metrics"
        state: directory
        owner: root
        group: root
        mode: 0755

    - file:
        path: "{{ docker_data_folder }}/metrics/grafana"
        state: directory
        owner: 472
        group: 472
        mode: 0755

    - file:
        path: "{{ docker_data_folder }}/metrics/prometheus"
        state: directory
        owner: nobody
        group: nogroup
        mode: 0755

    - file:
        path: "{{ docker_folder }}/metrics"
        state: directory
        owner: root
        group: root
        mode: 0755

    - template:
        src: env.j2
        dest: "{{ docker_folder }}/metrics/.env"
        owner: root
        group: root
        mode: 0700

    - copy:
        src: docker-compose.yml
        dest: "{{ docker_folder }}/metrics/docker-compose.yml"
        owner: root
        group: root
        mode: 0755

    - template:
        src: prometheus.yml.j2
        dest: "{{ docker_data_folder }}/metrics/prometheus.yml"
        owner: root
        group: root
        mode: 0755

- name: Run metrics directory
  docker_service:
    project_src: "{{ docker_folder }}/metrics"
    recreate: always
    build: yes
    nocache: yes
    state: present
