---
- name: Add Docker repository key.
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Install apt HTTPS transport and python-pip
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python3-pip
    update-cache: true
    cache_valid_time: 3600

- name: Add Docker repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Install Docker.
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
    update_cache: true
    cache_valid_time: 3600

#- name: Install docker-compose.
#  ansible.builtin.pip:
#    name:
#      - docker~=3.7.2
#      - docker-compose~=1.24.0
#    state: present

- name: Enable Docker.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Don't change iptables with Docker.
  ansible.builtin.lineinfile:
    dest: /etc/default/docker
    regexp: "^DOCKER_OPTS"
    line: 'DOCKER_OPTS="--iptables=false"'
    state: present
  notify: Restart docker

- name: Create docker directory.
  ansible.builtin.file:
    path: /srv/docker
    state: directory
    owner: root
    group: docker
    mode: "0755"
