#!/bin/bash
set -euo pipefail
set -x

cd "$(dirname "$0")"
#git pull

export TF_VAR_hetzner_token="$(gopass spaceapi/hetzner_cloud_token)"

function createAndProvision {
    local env=$1
    local domain=$2
    cd ../nodes
    terraform init
    terraform workspace select ${env}
    terraform apply -var-file=${env}.tfvars

    cd ../deployment
    env=${env} /usr/bin/env ansible-playbook -i inventory.sh playbooks/provisioning.yml --vault-password-file vaultpass --extra-vars "domain=$domain"
}

cd persistent
terraform init
terraform apply

read -p "Test changes in dev? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    createAndProvision dev spaceapi.rocks

    read -p "Dev deployed, press enter to destroy. Ctrl + C to cancel."

    # cleanup dev
    cd ../nodes
    terraform destroy -auto-approve -var-file=dev.tfvars
fi

read -p "Press enter to deploy to prod. Ctrl + C to cancel."
createAndProvision prod spaceapi.io
