#!/bin/bash
set -euo pipefail
set -x

cd "$(dirname "$0")"
TF_VAR_hetzner_token="$(gopass show spaceapi/hetzner_cloud_token)"
export TF_VAR_hetzner_token
TF_VAR_njalla_token="$(gopass show spaceapi/njalla_token)"
export TF_VAR_njalla_token

function autoDeploy {
    createPersistent

    read -p "Test changes in dev? " -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        createAndProvisionDev

        read -p "Dev deployed, press enter to destroy. Ctrl + C to cancel."
        destroyDev
    fi

    read -p "Press enter to deploy to prod. Ctrl + C to cancel."
    createAndProvisionProd
}

function createAndProvisionEnv {
    local env=$1
    local domain=$2
    local community_domain=$3

    cd nodes
    terraform init -upgrade
    terraform workspace select ${env}
    terraform apply -var-file=${env}.tfvars

    cd ../deployment
    env=${env} /usr/bin/env ansible-playbook -i inventory.sh playbooks/provisioning.yml --vault-password-file vaultpass --extra-vars "domain=$domain" --extra-vars "community_domain=$community_domain"
    cd ..
}

function createPersistent {
    cd persistent
    terraform init -upgrade
    terraform apply
    cd ..
}

function createAndProvisionProd {
    createAndProvisionEnv prod spaceapi.io spaceapi.community
}

function createAndProvisionDev {
    createAndProvisionEnv dev spaceapi.rocks community.spaceapi.rocks
}

function destroyDev {
    # cleanup dev
    cd nodes
    terraform workspace select dev
    terraform destroy -auto-approve -var-file=dev.tfvars
    cd ..
}

case ${1-} in
    destroydev) destroyDev; exit ;;
    deploydev) createAndProvisionDev; exit ;;
    *) autoDeploy; exit ;;
esac
