---
- name: Create service folder
  ansible.builtin.file:
    path: "{{ docker_folder }}/validator"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add docker-compose service configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ docker_folder }}/validator/.env"
    owner: root
    group: root
    mode: "0700"

- name: Add docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_folder }}/validator/docker-compose.yml"
    owner: root
    group: root
    mode: "0755"

- name: Run validator
  community.docker.docker_compose_v2:
    project_src: /etc/docker/validator
    recreate: always
    build: true
    pull: always
    state: present
