---
- name: Run validator
  docker_container:
    name: validator
    image: spaceapi/validator:master
    state: started
    recreate: yes
    restart: yes
    restart_policy: always
    networks:
      - name: traefik-web
    purge_networks: yes
    networks_cli_compatible: no
    labels:
      traefik.enable: "true"
      traefik.http.routers.validator.rule: "Host(`validator.{{ domain }}`)"
      traefik.http.routers.validator.tls.certresolver: "letsencrypt"
      com.centurylinklabs.watchtower.enable: "true"
