- name: Run validator
  docker_container:
    name: validator
    image: spaceapi/validator:master
    state: started
    recreate: yes
    restart: yes
    restart_policy: always
    networks:
      - name: traefik-web
    purge_networks: yes
    networks_cli_compatible: no
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik-web"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:validator.{{ domain }}"
