- name: Configure spaceapi directory
  block:
    - file:
        path: /etc/docker/spaceapi_directory
        state: directory
        owner: root
        group: root
        mode: 0755

    - copy:
        src: docker-compose.yml
        dest: /etc/docker/spaceapi_directory/docker-compose.yml
        owner: root
        group: root
        mode: 0755

- name: Run spaceapi directory
  docker_service:
    project_src: /etc/docker/spaceapi_directory
    recreate: always
    build: yes
    nocache: yes
    state: present
