---
- name: Create data directory
  file:
    path: "{{ docker_data_folder }}/mattermost/matterbridge"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy configuration
  template:
    src: matterbridge.j2
    dest: "{{ docker_data_folder }}/mattermost/matterbridge/matterbridge.toml"
    owner: root
    group: root
    mode: 0755

- name: Start matterbridge container
  docker_container:
    name: matterbridge
    image: 42wim/matterbridge:1.17.1
    state: started
    restart_policy: always
    volumes:
      - "{{ docker_data_folder }}/mattermost/matterbridge/matterbridge.toml:/matterbridge.toml"
