---
- name: Create service folder
  ansible.builtin.file:
    path: "{{ docker_folder }}/traefik"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add service configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ docker_folder }}/traefik/.env"
    owner: root
    group: root
    mode: "0700"

- name: Add docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_folder }}/traefik/docker-compose.yml"
    owner: root
    group: root
    mode: "0755"

- name: Create certificate folder
  ansible.builtin.file:
    path: "{{ docker_data_folder }}/traefik/acme"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure traefik
  ansible.builtin.copy:
    src: traefik.toml
    dest: "{{ docker_data_folder }}/traefik/traefik.toml"
    mode: "0744"

- name: Create additional config for traefik
  ansible.builtin.copy:
    src: "traefik_config/"
    dest: "{{ docker_data_folder }}/traefik/config"
    mode: "0744"

- name: Basic auth configuration
  ansible.builtin.template:
    src: basic_auth_middleware.toml.j2
    dest: "{{ docker_data_folder }}/traefik/config/basic_auth_middleware.toml"
    mode: "0744"

- name: Security header configuration
  ansible.builtin.template:
    src: security-headers.toml.j2
    dest: "{{ docker_data_folder }}/traefik/config/security-headers.toml"
    mode: "0744"

- name: Make sure traefik network exists
  community.docker.docker_network:
    name: traefik-web
    enable_ipv6: true
    state: present
    ipam_config:
      - subnet: 10.20.0.0/16
      - subnet: fd01::/80

- name: Run traefik
  community.docker.docker_compose:
    project_src: "{{ docker_folder }}/traefik"
    nocache: true
    state: present
