---
- name: Configure traefik
  block:
  - file:
      path: /etc/docker/traefik
      state: directory
      owner: root
      group: root
      mode: 0755

  - template:
      src: env.j2
      dest: /etc/docker/traefik/.env
      owner: root
      group: root
      mode: 0700

  - copy:
      src: docker-compose.yml
      dest: /etc/docker/traefik/docker-compose.yml
      owner: root
      group: root
      mode: 0755

  - file:
      path: "{{ docker_data_folder }}/traefik/acme"
      state: directory
      owner: root
      group: root
      mode: 0755

  - copy:
      src: traefik.toml
      dest: "{{ docker_data_folder }}/traefik/traefik.toml"

  - docker_network:
      name: traefik-web
      state: present

- name: Run traefik
  docker_compose:
    project_src: "{{ docker_folder }}/traefik"
    nocache: yes
    state: present
