version: "3.0"

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    volumes:
      - "${DATA_FOLDER}/victoriametrics:/storage:rw"
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
    networks:
      - default
    restart: always

  prometheus:
    image: "prom/prometheus:v2.10.0"
    depends_on:
      - victoriametrics
    networks:
      - default
      - traefik-web
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.port=9090"
    - "traefik.frontend.auth.basic.users=${BASIC_AUTH}"
    - "traefik.docker.network=traefik-web"
    - "traefik.frontend.rule=Host:prometheus.${DOMAIN}"
    volumes:
    - "${DATA_FOLDER}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    image: "grafana/grafana:6.2.4"
    depends_on:
      - prometheus
    networks:
      - default
      - traefik-web
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,raintank-worldping-app"
    volumes:
    - "${DATA_FOLDER}/grafana:/var/lib/grafana"
    labels:
    - "traefik.enable=true"
    - "traefik.port=3000"
    - "traefik.docker.network=traefik-web"
    - "traefik.frontend.rule=Host:metrics.${DOMAIN}"

networks:
  default:
  traefik-web:
    external: true
