version: "3.0"

services:
  victoriametrics:
    image: "victoriametrics/victoria-metrics:v1.27.2"
    volumes:
      - "${DATA_FOLDER}/victoriametrics:/storage:rw"
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=120"
      - "--httpListenAddr=:8428"
    networks:
      - default
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

  prometheus:
    image: "prom/prometheus:v2.10.0"
    depends_on:
      - victoriametrics
    networks:
      - default
      - traefik-web
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
    - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
    - "traefik.http.routers.prometheus.middlewares=secure-intern@file"
    - "com.centurylinklabs.watchtower.enable=true"
    volumes:
    - "${DATA_FOLDER}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    - "${DATA_FOLDER}/alert.rules:/alert.rules:ro"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - "${DATA_FOLDER}/alertmanager.yml:/alertmanager.yml:ro"
      - "${DATA_FOLDER}/alertmanager:/data"
    command:
      - "--config.file=/alertmanager.yml"
      - "--storage.path=/data"
    networks:
      - default
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.${DOMAIN}`)"
      - "traefik.http.routers.alertmanager.tls.certresolver=letsencrypt"
      - "traefik.http.routers.alertmanager.middlewares=secure-intern@file"
      - "com.centurylinklabs.watchtower.enable=true"

  grafana:
    image: "grafana/grafana:6.2.4"
    depends_on:
      - prometheus
    networks:
      - default
      - traefik-web
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,raintank-worldping-app"
      GF_SERVER_ROOT_URL: "https://metrics.${DOMAIN}"
      GF_AUTH_GITHUB_ENABLED: "true"
      GF_AUTH_GITHUB_CLIENT_ID: "73266238aea7c61b4e86"
      GF_AUTH_GITHUB_CLIENT_SECRET: "${GRAFANA_GITHUB_CLIENT_SECRET}"
      GF_AUTH_GITHUB_SCOPES: "user:email,read:org"
      GF_AUTH_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize"
      GF_AUTH_GITHUB_TOKEN_URL: "https://github.com/login/oauth/access_token"
      GF_AUTH_GITHUB_API_URL: "https://api.github.com/user"
      GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
      GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: "spaceapi spaceapi-community"
    volumes:
    - "${DATA_FOLDER}/grafana:/var/lib/grafana"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.metrics.rule=Host(`metrics.${DOMAIN}`)"
    - "traefik.http.routers.metrics.tls.certresolver=letsencrypt"
    - "com.centurylinklabs.watchtower.enable=true"

  cadvisor:
    image: google/cadvisor
    networks:
      - default
      - traefik-web
    restart: always
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.${DOMAIN}`)"
      - "traefik.http.routers.cadvisor.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cadvisor.middlewares=secure-intern@file"
      - "com.centurylinklabs.watchtower.enable=true"

  nodeexporter:
    image: quay.io/prometheus/node-exporter
    network_mode: "host"
    pid: "host"
    command: "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
  traefik-web:
    external: true
