---
- name: Create service folder
  ansible.builtin.file:
    path: "{{ docker_folder }}/github_bot"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add service configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ docker_folder }}/github_bot/.env"
    owner: root
    group: root
    mode: "0700"

- name: Add docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_folder }}/github_bot/docker-compose.yml"
    owner: root
    group: root
    mode: "0700"

- name: Run github_bot
  community.docker.docker_compose:
    project_src: "{{ docker_folder }}/github_bot"
    state: present
