---
- name: Create service folder
  block:
  - file:
      path: /etc/docker/github_bot
      state: directory
      owner: root
      group: root
      mode: 0755

  - template:
      src: env.j2
      dest: /etc/docker/github_bot/.env
      owner: root
      group: root
      mode: 0700

  - copy:
      src: docker-compose.yml
      dest: /etc/docker/github_bot/docker-compose.yml
      owner: root
      group: root
      mode: 0700

- name: Run github_bot
  docker_compose:
      project_src: "/etc/docker/github_bot"
      state: present
