- name: Run website
  docker_container:
    name: website
    image: spaceapi/website:v3
    state: started
    restart_policy: always
    networks:
      - name: traefik-web
    purge_networks: yes
    networks_cli_compatible: no
    labels:
      traefik.enable: "true"
      traefik.http.routers.website.rule: "Host(`{{ domain }}`)"
      traefik.http.routers.website.tls.certresolver: "letsencrypt"
      com.centurylinklabs.watchtower.enable: "true"
