---
- name: Run website
  docker_container:
    name: website
    image: spaceapi/website:v3
    state: started
    restart_policy: always
    networks:
      - name: traefik-web
    purge_networks: yes
    networks_cli_compatible: no
    labels:
      traefik.enable: "true"
      traefik.http.routers.website.rule: "Host(`{{ domain }}`) || Host(`www.{{ domain }}`)"
      traefik.http.routers.website.tls.certresolver: "letsencrypt"
      traefik.http.routers.website.tls.options: "default"
      traefik.http.routers.website.middlewares: "security-headers@file"
      traefik.http.services.website.loadbalancer.server.port: "8080"
      com.centurylinklabs.watchtower.enable: "true"
