- name: Run website
  docker_container:
    name: website
    image: spaceapi/website:v3
    state: started
    recreate: yes
    restart_policy: always
    networks:
      - name: traefik-web
    purge_networks: yes
    networks_cli_compatible: no
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik-web"
      traefik.port: "80"
      traefik.frontend.rule: "Host:{{ domain }}"
      com.centurylinklabs.watchtower.enable: "true"

