---
- hosts: node1
  user: root
  roles:
    # server setup
    - { role: storage }
    - { role: base, tags: ['base'] }
    - { role: motd, tags: ['motd'] }
    - { role: docker, tags: ['docker'] }
    - { role: watchtower, tags: ['watchtower'] }
    - role: ssh_access
      vars:
        ssh_access_github_user:
          - gidsi
          - dbrgn
          - rnestler
          - s3lph
      tags: access

    # services
    - { role: website, tags: ['website'] }
    - { role: schema, tags: ['schema'] }
    - { role: directory, tags: ['directory'] }
    - { role: swagger, tags: ['swagger'] }
    - { role: validator, tags: ['validator'] }
    - { role: metrics, tags: ['metrics'] }
