---
- hosts: node1
  # become: yes
  user: root
  roles:
    - { role: network }
    - { role: storage }
    - { role: base, tags: ['base'] }
    - { role: mattermost, tags: ['mattermost'] }
    - { role: matterbridge, tags: ['matterbridge'] }
    - { role: motd, tags: ['motd'] }
    - { role: docker, tags: ['docker'] }
    - { role: watchtower, tags: ['watchtower'] }
    - { role: website, tags: ['website'] }
    - { role: directory, tags: ['directory'] }
    - { role: validator, tags: ['validator'] }
    - { role: metrics, tags: ['metrics'] }
