version: '3'

services:
  reverse-proxy:
    image: traefik:1.7.9
    command: --api --docker
    restart: always
    networks:
     - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-web"
      - "traefik.frontend.rule=Host:reverseproxy.${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_FOLDER}/acme:/etc/traefik/acme
      - ${DATA_FOLDER}/traefik.toml:/etc/traefik/traefik.toml

networks:
  traefik-web:
    external: true
