version: '3'

services:
  reverseproxy:
    image: traefik:v2.11
    restart: always
    networks:
      - traefik-web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.reverseproxy.rule=Host(`reverseproxy.${DOMAIN}`)"
      - "traefik.http.routers.reverseproxy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.reverseproxy.service=api@internal"
      - "traefik.http.routers.reverseproxy.middlewares=secure-intern@file"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_FOLDER}/acme:/etc/traefik/acme
      - ${DATA_FOLDER}/:/etc/traefik/

networks:
  traefik-web:
    external: true
