---
- name: Run watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower:1.1.4
    state: started
    restart_policy: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "--interval {{ watchtower_interval }} --cleanup --label-enable"
    env:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://chat.{{ domain }}/hooks/{{ vault_watchtower_mattermost_token }}"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: watchtower-katharina
