version: "3.7"

services:
  bot:
    image: spaceapi/github-bot
    restart: always
    environment:
      WEBHOOK_PROXY_URL: ${WEBHOOK_PROXY_URL}
      APP_ID: ${APP_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      DB_HOST: "database"
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.githubbot.rule=Host(`githubbot.${DOMAIN}`)"
      - "traefik.http.middlewares.githubbot-addspaceapi.addprefix.prefix=/spaceapi"
      - "traefik.http.routers.githubbot.middlewares=githubbot-addspaceapi"
      - "traefik.http.routers.githubbot.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - traefik-web
  database:
    image: mongo:7
    restart: always
    volumes:
      - "${DATA_FOLDER}/db:/data/db"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default

networks:
  traefik-web:
    external: true
  default:
