---
- name: Run schema server
  community.docker.docker_container:
    name: schema
    image: spaceapi/schema:latest
    state: started
    restart_policy: always
    networks:
      - name: traefik-web
    purge_networks: true
    networks_cli_compatible: false
    labels:
      traefik.enable: "true"
      traefik.http.routers.schema.rule: "Host(`schema.{{ domain }}`)"
      traefik.http.routers.schema.tls.certresolver: "letsencrypt"
      traefik.http.routers.schema.tls.options: "default"
      traefik.http.routers.schema.middlewares: "security-headers@file"
      traefik.http.services.schema.loadbalancer.server.port: "80"
      com.centurylinklabs.watchtower.enable: "true"
