version: "2"

services:
  db:
    image: mattermost/mattermost-prod-db:5.12.0
    restart: always
    volumes:
      - ${DATA_FOLDER}/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - default
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mattermost
  app:
    image: mattermost/mattermost-prod-app:5.12.0
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - ${DATA_FOLDER}/app/mattermost/config:/mattermost/config:rw
      - ${DATA_FOLDER}/app/mattermost/data:/mattermost/data:rw
      - ${DATA_FOLDER}/app/mattermost/logs:/mattermost/logs:rw
      - ${DATA_FOLDER}/app/mattermost/plugins:/mattermost/plugins:rw
      - ${DATA_FOLDER}/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=${POSTGRES_PASSWORD}
      - MM_DBNAME=mattermost
    depends_on:
      - db
  web:
    image: mattermost/mattermost-prod-web:5.12.0
    expose:
      - "80"
    restart: always
    networks:
      - traefik-web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-web"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:chat.${DOMAIN}"
    volumes:
      - ${DATA_FOLDER}/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app

  githubintegration:
    build: githubintegration/.
    restart: always
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:gh.chat.${DOMAIN}"
    expose:
      - "5000"

networks:
  default:
  traefik-web:
    external: true
