FROM python:3-alpine

RUN apk update && apk upgrade && \
  apk add --no-cache git build-base python-dev py-pip jpeg-dev zlib-dev

RUN git clone https://github.com/softdevteam/mattermost-github-integration.git
WORKDIR /mattermost-github-integration
RUN pip install -r requirements.txt

ADD config.py /mattermost-github-integration/mattermostgithub/config.py

CMD python server.py