- name: Deploy mattermost + matterbridge
  block:
      - file:
          path: "{{ docker_data_folder }}/mattermost"
          state: directory

      - file:
          path: "{{ docker_data_folder }}/mattermost/matterbridge"
          state: directory

      - file:
          path: /etc/docker/mattermost
          state: directory

      - template:
          src: env.j2
          dest: /etc/docker/mattermost/.env

      - copy:
          src: docker-compose.yml
          dest: /etc/docker/mattermost/docker-compose.yml

      - template:
          src: matterbridge.j2
          dest: "{{ docker_data_folder }}/mattermost/matterbridge/matterbridge.toml"

- name: Run mattermost + matterbridge
  docker_service:
    project_src: /etc/docker/mattermost
    state: present
