version: '3'

services:
  web:
    image: spaceapi/directory
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:directory.spaceapi.net,directory.spaceapi.io"

networks:
  traefik-web:
    external: true
