version: '3'

services:
  web:
    image: nginx
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:directory.spaceapi.net,directory.spaceapi.io"
    volumes:
      - ${DATA_FOLDER}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  traefik-web:
    external: true
