- name: Run website
  docker_container:
    name: website
    image: spaceapi/website:v2
    state: started
    recreate: yes
    restart: yes
    restart_policy: always
    networks:
      - name: traefik-web
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik-web"
      traefik.port: "80"
      traefik.frontend.rule: "Host:spaceapi.io"
