- name: Update apt cache.
  apt: update-cache=yes cache_valid_time=3600

- name: Install required system packages.
  apt: pkg={{ item }} update-cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - gcc
    - g++
    - unattended-upgrades

- name: Unattended upgrades - copy config file
  template: src=unattended_upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644

- name: Apt - periodic updates.
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root mode=0644
