---
- name: Create service data directory
  ansible.builtin.file:
    path: "{{ docker_data_folder }}/mattermost"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create service directory
  ansible.builtin.file:
    path: "{{ docker_folder }}/mattermost"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add service configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ docker_folder }}/mattermost/.env"
    owner: root
    group: root
    mode: "0700"

- name: Add docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_folder }}/mattermost/docker-compose.yml"
    owner: root
    group: root
    mode: "0755"

- name: Run mattermost + integrations
  community.docker.docker_compose:
    project_src: "{{ docker_folder }}/mattermost"
    state: present
