version: '3'

services:
  web:
    image: nginx
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:directory.${DOMAIN}"
    volumes:
      - "${DATA_FOLDER}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
  api:
    image: spaceapi/directory-api
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - default
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:api.${DOMAIN}"
      - "traefik.docker.network=traefik-web"
  collector:
    image: spaceapi/directory-collector
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:api.${DOMAIN};PathPrefixStrip:/collector"
      - "traefik.docker.network=traefik-web"
    networks:
      - default
      - traefik-web
    volumes:
      - "${DATA_FOLDER}:/srv/spaceapi"

networks:
  traefik-web:
    external: true
  default:
