version: '3'

services:
  directory:
    image: nginx
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory.rule=Host(`directory.${DOMAIN}`)"
      - "traefik.http.routers.directory.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - "${DATA_FOLDER}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
  api:
    image: ghcr.io/spaceapi/directory-api
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - default
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory-api.rule=Host(`api.${COMMUNITY_DOMAIN}`)"
      - "traefik.http.routers.directory-api.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
  collector:
    image: ghcr.io/spaceapi/directory-collector
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory-collector.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.directory-collector.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - traefik-web
    volumes:
      - "${DATA_FOLDER}:/srv/spaceapi"

networks:
  traefik-web:
    external: true
  default:
