---
- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required system packages.
  ansible.builtin.apt:
    pkg:
      # Base
      - build-essential
      - gcc
      - g++
      # Sysadmin
      - htop
      - strace
      - vim-nox
      - mlocate
      - curl
      - molly-guard
      # Security
      - unattended-upgrades
      - apt-listchanges
      - gnupg
      - python-setuptools
      - python3-pip
    update_cache: true
    cache_valid_time: 3600

- name: Unattended upgrades - copy config file
  ansible.builtin.template:
    src: unattended_upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Apt - periodic updates.
  ansible.builtin.copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
